name: Docker Image Build on tag or release

on:
  push:
    tags:
      - '*'
  release:
    types:
      - published

env:
  ORG: opentelekomcloud
  PROJECT: openapi-validator

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            "${{ secrets.REGISTRY }}/${{ env.ORG }}/${{ env.PROJECT }}"
          tags: |
            type=semver,pattern={{version}},prefix=v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
